name: Node CI

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:
    name: Build and test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - name: Run ESLint
        if: startsWith(matrix.os,'ubuntu')
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint_flags: './src/ --ext .js,.jsx,.ts,.tsx'

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Build app
        run: |
          npm run build --if-present
        env:
          CI: true
