name: Node CI

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:
    name: Build and test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hallee/eslint-action@master
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}


      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: Run tests
        run: npm test
        env:
          CI: true
